"""empty message

Revision ID: 12a1d416b35e
Revises: d6639af18a56
Create Date: 2024-03-14 23:42:08.977150

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '12a1d416b35e'
down_revision: Union[str, None] = 'd6639af18a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('lyrics', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'lyrics')
    # ### end Alembic commands ###
