"""empty message

Revision ID: 4a14745ef9f8
Revises: 52236ce91805
Create Date: 2024-03-27 20:24:03.071627

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.sql import column, table

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a14745ef9f8"
down_revision: Union[str, None] = "52236ce91805"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("track", sa.Column("filename_original", sa.String(), nullable=True))

    track = table(
        "track",
        column("filename_vocals", sa.String()),
        column("filename_original", sa.String()),
    )

    op.execute(track.update().values(filename_original=track.c.filename_vocals))

    op.alter_column("track", "filename_original", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("track", "filename_original")
    # ### end Alembic commands ###
