"""empty message

Revision ID: 52236ce91805
Revises: a7f61a8fe7e5
Create Date: 2024-03-26 12:41:08.279987

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "52236ce91805"
down_revision: Union[str, None] = "a7f61a8fe7e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "track",
        sa.Column(
            "is_favorite", sa.Boolean(), nullable=False, server_default=sa.text("FALSE")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("track", "is_favorite")
    # ### end Alembic commands ###
