"""empty message

Revision ID: a7f61a8fe7e5
Revises: 4a303689767f
Create Date: 2024-03-22 14:43:31.790523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f61a8fe7e5'
down_revision: Union[str, None] = '4a303689767f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('lyrics_karaoke', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'lyrics_karaoke')
    # ### end Alembic commands ###
