"""empty message

Revision ID: b46fbe9d06e4
Revises: b3d2a87ec36d
Create Date: 2024-03-13 00:30:39.741463

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b46fbe9d06e4'
down_revision: Union[str, None] = 'b3d2a87ec36d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('source_info', sa.JSON(), nullable=False))
    op.drop_column('album', 'source_url')
    op.add_column('song', sa.Column('filename_original', sa.String(), nullable=False))
    op.add_column('song', sa.Column('filename_instrumental', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'filename_instrumental')
    op.drop_column('song', 'filename_original')
    op.add_column('album', sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('album', 'source_info')
    # ### end Alembic commands ###
