"""Create song + add relationships

Revision ID: f624d0186ad2
Revises: b20480ab6439
Create Date: 2024-03-10 19:04:42.154522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f624d0186ad2'
down_revision: Union[str, None] = 'b20480ab6439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('album', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('album', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('album', 'name')
    op.drop_table('song')
    # ### end Alembic commands ###
